---
- name: Configure nginx config file
  become: true
  template:
    src: django-nginx.conf
    dest: /etc/nginx/sites-enabled/django-{{django_project_name}}-{{django_project_environment}}.conf
  notify:
    - restart nginx

- name: Create socket directory
  become: true
  file:
    path: '{{django_uwsgi_socket_dir}}'
    state: directory

- name: Configure uwsgi app
  become: true
  template:
      src: django-uwsgi.ini
      dest: '/etc/uwsgi/apps-available/{{uwsgi_project_name}}.ini'
  notify:
    - restart uwsgi

- name: Enable uwsgi app
  become: true
  file:
      dest: '/etc/uwsgi/apps-enabled/{{uwsgi_project_name}}.ini'
      src: '/etc/uwsgi/apps-available/{{uwsgi_project_name}}.ini'
      state: link
  notify:
    - restart uwsgi
