---
- name: Configure nginx config file
  become: true
  template:
    src: django-nginx.conf
    dest: /etc/nginx/sites-available/{{project_config_name}}.conf
  notify:
    - restart nginx

- name: Enable nginx app
  become: true
  file:
    src: /etc/nginx/sites-available/{{project_config_name}}.conf
    dest: /etc/nginx/sites-enabled/{{project_config_name}}.conf
    state: link
  notify:
    - restart nginx

- name: Create socket directory
  become: true
  file:
    path: '{{django_uwsgi_socket_dir}}'
    state: directory

- name: Configure uwsgi app
  become: true
  template:
      src: django-uwsgi.ini
      dest: '/etc/uwsgi/apps-available/{{project_config_name}}.ini'
  notify:
    - restart uwsgi

- name: Enable uwsgi app
  become: true
  file:
      dest: '/etc/uwsgi/apps-enabled/{{project_config_name}}.ini'
      src: '/etc/uwsgi/apps-available/{{project_config_name}}.ini'
      state: link
  notify:
    - restart uwsgi

- name: Configure letsencrypt
  become: true
  shell: 'certbot -n --nginx --agree-tos --domains {{django_server_name.split(" ") | join(",")}}'
  register: result
  changed_when: '"Keeping" not in result.stdout'
